config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :items
  devise_for :stars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 root 'users#show'
 resources :users

 resources :items do
	resource :stars, only: [:create, :destroy]
 end
 # 子要素にするのでdo endで囲む

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

	belongs_to :user
	has_many :stars, dependent: :destroy
	validates :item_name, presence: true

	def starred_by?(user)
    stars.where(user_id: user.id).exists?
  end
  # starred_by?メソッド(別名_by?でもOK)で、引数で渡されたユーザのidがstarsテーブル内にexists?しているか調べる。
  # 存在していればTrue、存在していなければFalseを返すようにしている。

  scope :get_by_category, ->(category) { where("category like ?", "%#{category}%") } # categoryによる絞り込み
	scope :get_by_item_name, ->(item_name) { where("item_name like ?", "%#{item_name}%") }

end

app/models/star.rb
class Star < ApplicationRecord

  belongs_to :user
  belongs_to :item

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :stars, dependent: :destroy
  accepts_nested_attributes_for :items, allow_destroy: true

  validates :name, presence: true
  validates :encrypted_password, presence: true, uniqueness: true, length: { minimum: 4 }

  def email_required?
    false
  end

  def email_changed?
    false
  end
  # email_required?とemail_changed?をオーバーライドし、falseを返却するようにしておく。これをしないと、登録時にemailが必須になる。

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:new_user_registration_path, :new_user_session_path]

  protect_from_forgery with: :exception #protect_from_forgery： CSRF対策用メソッド
  before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		user_path(current_user.id)
	end

	def after_sign_out_path_for(resource)
		new_user_session_path
	end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  # configure_permitted_parametersでは、devise_parameter_sanitizer.permitでnameのデータ操作を許可するアクションメソッドが指定されている。
  # 今回の場合、ユーザ登録(sign_up)の際、ユーザ名(name)のデータ操作が許可されることになる。
  # ストロングパラメータと同様。
  # privateは自分のコントローラ内でしか参照できないが、protectedは呼び出された他のコントローラからも参照ができるストロングパラメータとなる。

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_action :authenticate_user!, except: [:new_user_registration_path, :new_user_session_path]

	def create
		@item = Item.new(item_params)
		@item.user_id = current_user.id #userの存在しないitemができないよう、save前にuserを保存
		@item.save
		flash.now[:notice] = "登録しました"
		redirect_to user_path(current_user.id)
	end

	def edit
		@item = Item.find(params[:id])
		@items = Item.all
	end

	def update
		item = Item.find(params[:id])
		item.update(item_params)
		flash.now[:notice] = "更新しました"
		redirect_to user_path(current_user.id)
	end


	def destroy
    item = Item.find(params[:id])
    item.destroy
    flash[:notice] = '削除しました'
    redirect_to user_path(current_user.id)
	end


	private
		def item_params
			params.require(:item).permit(:user_id, :item_name, :item_quantity, :price, :weight, :item_memo_one, :deadline, :unit, :category, 
				:subcategory, :item_image_id, :notice_day, :author, :maker, :color, :size, :use_place, :purchase_place, :item_memo_two, :price_unit )
		end

end

app/controllers/stars_controller.rb
class StarsController < ApplicationController

  before_action :authenticate_user!, except: [:new_user_session_path, :new_user_registration_path]

	def create
    item = Item.find(params[:item_id])
    star = current_user.stars.new(item_id: item.id)
    star.save
    redirect_to user_path(current_user.id)
  end

  def destroy
    item = Item.find(params[:item_id])
    star = current_user.stars.find_by(item_id: item.id)
    star.destroy
    redirect_to user_path(current_user.id)
   end

   private
		def star_params
			params.require(:item).permit(:item_id, :user_id)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!, except: [:new_user_registration_path, :new_user_session_path] #deviceのメソッド、ログイン未認証ならrootパスへリダイレクトする機能を実装。未ログインのユーザーはshowにアクセス不可

	def show
		@item = Item.new
		@user = User.find(current_user.id)
		@items = @user.items.all

		if params[:item_name].present?
			@items = @items.get_by_item_name params[:item_name]
	  end
	  if params[:category].present?
			@items = @items.get_by_category params[:category]
	  end
	  unless @items.count == Item.all.count # itemsの数がitems.allから変わっているか確認
		if @items.count == 0 # itemsの数が０の時
		  @items = @user.items.all #@items = Item.all にするとユーザーAの登録内容がユーザーBでログイン時にも出てしまう
		  flash.now[:notice] = "登録されていません"
		  render :action => :show and return  # showに戻り、renderをもう一度使いたいのでreturn
		elsif @items.count > 0
      flash.now[:notice] = "#{@items.count}件ありました" #{@items.count}で絞り込まれた数を表示させる
      render :action => :show and return # renderにする事で変更された情報を維持しつつnoticeを表示させる
		end
	  end
	end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = '更新しました'
    redirect_to user_path(current_user.id)
	end

	def destroy
    user = User.find(current_user.id)
    # if admin_signed_in?
    #   user.destroy
    #   redirect_to users_path
    # else
      user.destroy
      redirect_to new_user_registration_path
  end

	private
		def user_params
			params.require(:user).permit(:name,
				items_attributes: [:item_name, :item_quantity, :price, :weight, :item_memo_one, :deadline, :unit, 
													:category, :subcategory, :item_image_id, :notice_day, :author, :maker, :color, :size, :use_place, 
													:purchase_place, :item_memo_two, :price_unit, :_destroy])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<div class="background_img_edit">
	<div class="table_edit">
		<%= form_for(@item) do |f| %>
			<table>
				<tbody>
					<tr>
						<th class="th_edit"> カテゴリー </th>
						<th class="th_edit"> サブカテゴリー </th>
						<th class="th_edit"> アイテム名 </th>
						<th class="th_edit"> 数量 </th>
						<th class="th_edit"> 数量の単位 </th>
						<th class="th_edit"> 価格 </th>
						<th class="th_edit"> 価格の単位 </th>
						<th class="th_edit"> 重量(g) </th>
						<th class="th_edit"> 期限 </th>
						<th class="th_edit"> メモ </th>
					</tr>

					<tr>
						<td class="th_edit"> </td>
						<td class="th_edit"> </td>
						<td class="th_edit"> <small> ここだけ必須 </small> </td>
						<td class="th_edit"> <small> 小数OK </small> </td>
						<td class="th_edit"> <small> 文字・記号OK </small> </td>
						<td class="th_edit"> <small> 小数OK </small> </td>
						<td class="th_edit"> <small> 文字・記号OK </small> </td>
						<td class="th_edit"> <small> グラム </small> </td>
					</tr>

						<td> <%= f.text_area :category, size: "15x1" %> </td>
						<td> <%= f.text_area :subcategory, size: "15x1" %> </td>
						<td> <%= f.text_area :item_name, size: "15x1" %> </td>
						<td> <%= f.text_area :item_quantity, size: "14x1" %> </td>
						<td> <%= f.text_area :unit, size: "14x1" %> </td>
						<td> <%= f.text_area :price, size: "14x1" %> </td>
						<td> <%= f.text_area :price_unit, size: "14x1" %> </td>
						<td> <%= f.text_area :weight, size: "14x1" %> </td>
						<td> <%= f.text_area :deadline, size: "15x1" %>  </td>
						<td> <%= f.text_area :item_memo_one, size: "15x1" %> </td>
						<td>&emsp;</td>
						<td> <%= f.submit '更新', class: 'btn btn-lg btn-success', "data-disable-with" => "更新中..." %> </td> <p>&emsp;</p>
						<td>&emsp;</td>
						<td> <%= link_to "戻る", user_path(current_user.id), class: 'btn btn-primary' %> </td>
					</tbody>
			</table>
			<%#= link_to "一覧に戻る", user_path(current_user.id), class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html> <!-- ドキュメントタイプと言い、このHTMLファイルがどのバージョンを使って書かれているかを宣言するタグ。ブラウザがHTMLファイルとして認識するために必要なので必須 -->
<html> <!-- lang="ja"属性は、SEO目的だと無意味 -->

  <head>
    <meta charset="UTF-8">
    <!-- meta要素は、文章に関する情報を指定するもの。"UTF-8"は文字コードといい、コンピュータでの文字の処理方法を指定している。これが未指定だと文章が文字化けする -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <!-- viewportの幅は端末やブラウザアプリ毎によって異なる。端末ごとのサイズに応じてフレキシブルな表示ができる一方、細かい表示の統一はやりづらい。上記はcontent属性は「サイトを開いたときの倍率は等倍」 -->
    <title>ATTO</title>
    <!-- HTMLファイルがどういうページなのかを示すためのタイトルを記述。ページ上には反映されず、ブラウザのツールバーや検索エンジンの検索結果のページ名となる -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <!-- Font Awesome導入、style.cssの記述よりも上に配置 -->
    <link rel="stylesheet" href="style.css">
    <!-- HTMLファイルからCSSファイルを読み込むために必須、下の方が重要度高くなるので自分の記述したスタイルは一番下 -->
    <!-- linkタグのrel属性： 現在のファイルとリンク先の外部ファイルとの関係性を表すキーワード（cssならstylesheetと記述） -->
    <!-- linkタグのhref属性： 読み込むファイル名を書くことで、HTMLファイルに外部ファイルを読み込ませる（作ったcssファイルの名前を記述） -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script type="text/javascript" src="main.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/users/show.html.erb
<div class="background_img_show col-xs-12 col-lg-12">
	<div>
		<%= form_for(@item) do |f| %>
				<table>
					<tbody>
						<tr>
							<th> <i>&emsp;</i>カテゴリー </th>
							<th> <i>&emsp;</i>サブカテゴリー </th>
							<th> <i>&emsp;</i>アイテム名 </th>
							<th> <i>&emsp;</i>数量 </th>
							<th> <i>&emsp;</i>数量の単位 </th>
							<th> <i>&emsp;</i>価格 </th>
							<th> <i>&emsp;</i>価格の単位 </th>
							<th> <i>&emsp;</i>重量(g) </th>
							<th> <i>&emsp;</i>期限 </th>
							<th> <i>&emsp;</i>メモ </th>
						</tr>
							<td> <%= f.text_area :category, size: "15x1" %> </td>
							<td> <%= f.text_area :subcategory, size: "15x1" %> </td>
							<td> <%= f.text_area :item_name, size: "15x1", placeholder: "ここだけ必須" %> </td>
							<td> <%= f.text_area :item_quantity, size: "14x1", placeholder: "小数OK" %> </td>
							<td> <%= f.text_area :unit, size: "14x1", placeholder: "文字・記号OK" %> </td>
							<td> <%= f.text_area :price, size: "14x1", placeholder: "小数OK" %> </td>
							<td> <%= f.text_area :price_unit, size: "14x1", placeholder: "文字・記号OK" %> </td>
							<td> <%= f.text_area :weight, size: "14x1", placeholder: "グラム" %> </td>
							<td> <%= f.text_area :deadline, size: "15x1" %> </td>
							<td> <%= f.text_area :item_memo_one, size: "15x1" %> </td>
							<td>&emsp;</td>
							<td> <%= f.submit '登録', class: 'btn-lg btn-success', "data-disable-with" => "登録中..." %> </td>
					</tbody>
				</table>
			<%#= f.submit '登録', class: "btn-lg btn-success" %>
		<% end %>
	</div>



<!-- タブ -->
	<script>
		jQuery(function($){
	    $('.tabcontent > div').hide();

	    $('.tabnav a').click(function () {
	    	$('.tabcontent > div').hide().filter(this.hash).fadeIn();

	    	$('.tabnav a').removeClass('active');
	    	$(this).addClass('active');

	    	return false;
	    }).filter(':eq(0)').click();
		});
	</script>
<!-- タブここまで -->


	<!-- DD(tbodyにid="sort") -->
	<script>
		$(function() {
		  $('#sort').sortable();
		});
	</script>
	<!-- DDここまで -->


<div class="col-xs-12 col-lg-12">
  <%= form_tag(user_path(current_user.id), method: "get") do %>
  <%= label_tag :category, "カテゴリー名で検索" %>
  <%= text_field_tag :category, params[:category] %>
  <%= button_tag( class: " btn-primary") do %>
  <%= content_tag :span, "", class: "glyphicon glyphicon-search" %>
  <% end %>
  <% end %>
</div>

<div class="col-xs-12 col-lg-12">
	<%= form_tag(user_path(current_user.id), method: "get") do %>
	<%= label_tag :item_name, "アイテム名で検索" %><i>&emsp;</i>
  <%= text_field_tag :item_name, params[:item_name] %>
  <%= button_tag( class: " btn-primary") do %>
  <%= content_tag :span, "", class: "glyphicon glyphicon-search" %>
  <% end %>
  <% end %>
</div>
<div> &nbsp; </div>

	<div class="col-xs-12 col-lg-12">
		<ul class="tabnav">
	    <li>
	    	<a href="#tab01">
	    		<%= @user.name %> のタブ （登録数<i>&emsp;</i><%= @items.count %>）
	    	</a>
	    </li>
	    <li>
	    	<a href="#tab02">
	    		メニュー
	    	</a>
	    </li>
		</ul>

		<div class="tabcontent">
	    <div id="tab01">

		    	<div class="search-results col-md-offset-5">
						<strong> <%= flash[:notice] %> </strong>
					</div><br>

				<div style="height:550px; overflow-y:auto;">
		    	<table class="table table-hover table-bordered">
						<thead class="item_thead">
							<th> ☆ </th>
							<th> カテゴリー </th>
							<th> サブカテゴリー </th>
							<th> アイテム名 </th>
							<th> 数量 </th>
							<th> 数量の単位 </th>
							<th> 価格 </th>
							<th> 価格の単位 </th>
							<th> 単価 </th>
							<th> 重量(g) </th>
							<th> 期限 </th>
							<th class="col-xs-2"> メモ </th>
							<th> 編集 </th>
							<th> 削除 </th>
						</thead>

						<tbody class="item_tbody" id="sort">
							<% @items.each do |item| %>
								<tr>
									<!-- <td> <%#= check_box_tag :item_name %> </td> -->

									<td>
										<% if item.starred_by?(current_user) %>
									    <%= link_to item_stars_path(item), method: :delete do %>
								      <p class="glyphicon glyphicon-star" aria-hidden="true" style="color: red; font-size:25px"></p>
								      <!-- <p class="fa fa-heart" aria-hidden="true" style="color: red;"></p> -->
								    <% end %>
										<% else %>
									    <%= link_to item_stars_path(item), method: :post do %>
								      <p class="glyphicon glyphicon-star-empty" aria-hidden="true" style="font-size:25px"></p>
									    <% end %>
										<% end %>
									</td>

									<td> <%= item.category %> </td>
									<td> <%= item.subcategory %> </td>
									<td> <%= item.item_name %> </td>

									<td>
										<%# if item.item_quantity.nil? %>
										<% if item.item_quantity == nil %>
											<%= "" %>
										<% else %>
											<%= number_with_delimiter(item.item_quantity.round(2)) %>
										<% end %>
									</td>

									<td> <%= item.unit %> </td>
									<td> <%= number_with_delimiter(item.price) %> </td>
									<td> <%= item.price_unit %> </td>

									<td>
										<%# binding.pry %>
										<% if item.price.nil? or item.item_quantity.nil? %>
											<%= "" %>
										<% else %>
											<%= number_with_delimiter((item.price / item.item_quantity).round(2)) %>
										<% end %>
									</td>

									<td> <%= number_with_delimiter(item.weight) %> </td>

									<td>
										<% if item.deadline == nil %>
											<%= "" %>
										<% else %>
											<%= item.deadline.strftime('%Y/%m/%-d (%a)') %>
										<% end %>
									</td>

									<td style="word-wrap:break-word;"> <%= item.item_memo_one %> </td>

									<%# if @items == current_user %>
										<td> <%= link_to '編集', edit_item_path(item), class: "btn btn-success" %> </td>
									<%# elsif %>
										<!-- <td> .. </td> -->
									<%# end %>

										<td> <%= link_to "", item_path(item), method: :delete, class: "glyphicon glyphicon-remove-circle", style: "font-size:25px;", "data-confirm" => "この項目を削除します"%> </td> <!-- item_pathでitem Cに行く、each文で既に1件ずつになっているので()に含む -->

								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
	    </div>


	    <div id="tab02">
	    	<div> <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %> </div> <br>

				<div class="popupModal1">
				 	<input type="radio" name="modalPop" id="pop11" />
				 	<label for="pop11", class="btn btn-success"> 登録情報変更 </label>
				 	<input type="radio" name="modalPop" id="pop12" />
				 	<label for="pop12">CLOSE</label>
				 	<input type="radio" name="modalPop" id="pop13" />
				 	<label for="pop13">×</label>
				 	<div class="modalPopup2">
				  	<div class="modalPopup3">
				   		<h4 class="modalTitle"> お名前を変更しますか？ </h4>
				   		<div class="modalMain">
				   			<label> 現在のお名前：&nbsp;<%= @user.name %> </label>
				   			<div> ↓ </div>
					    	<%= form_for(@user) do |f| %>
							    <label>変更後のお名前：</label>
							    <%= f.text_field :name, autofocus: true %><br>
							    <div> <%= f.submit "変更", class:"btn btn-success", "data-disable-with" => "変更中..." %> </div>
								<% end %>
				   		</div>
				  	</div>
				 	</div>
				</div><br>

				<div>
					<a class="fab fa-facebook-square" href="https://www.facebook.com/sharer/sharer.php?u=http://qiita.com/katsuma"> Facebook </a>
					<a class="fab fa-twitter-square" href="http://twitter.com/share?url=http://qiita.com/katsuma"> Twitter </a>
	    		<a class="fab fa-line" href="http://line.me/R/msg/text/?http://qiita.com/katsuma"> LINE </a>
	    	</div> <br>

	    	<div>
	    		<%= link_to "アカウント削除", user_path(current_user.id), class: 'btn btn-danger', method: :delete, "data-confirm" => "データはすべて削除され、復元できません。よろしいですか？" %>
	    	</div>

			</div>

		</div>
	</div>
</div>